### ISSUE TITLE
[Bug] Wrong match starting time

### ISSUE THREAD

**Issue by lluni** [kcapp/api#17]
Since updating to 2.3.0 the starting time is always 1 hour behind what it should be.
The API seems to use UTC now rather than the local timezone (in my case CET or UTC+1) which was probably introduced in 0d6200b329585bc224d21930067123bbf456bd80.

So now a typical match looks like this:
![image](https://user-images.githubusercontent.com/36239317/158282227-58a6a931-5837-47ee-a054-bd23a711af1b.png)
The ending time and the duration are correct but the starting time is 1 hour behind.

The problem is probably because `data/match.go` inserts `NOW().UTC()` as the starting time but reads the ending time from the last leg in that match which was inserted as `NOW()` in `data/leg.go`. In that case the `UTC()` call can just be removed.

**Comment by thordy** [comment]
Hi @lluni , 
Thanks for the report. This has been an issue for a while, and it seems my attempt to "fix" it didn't really work. Sorry about that.
The goal would be to only use `UTC` in database and backend, to avoid all kinds of issues with mixed timezones.

I think keeping it all as `UTC` on the backend makes sense, and instead add timezone to all datetimes returned by the API, and see if we can make the frontend use timezone of browser when displaying them.

Would that work for you?

**Comment by lluni** [comment]
Maybe if using the timezone of the browser doesn't work, you could use a `TZ`/`Timezone` docker environment variable or directly the container/host timezone (a docker volume mount `"/etc/timezone:/etc/timezone:ro"` for the frontend container could be used for that).

**Comment by thordy** [comment]
I switched from using `string` to `time.Time` for all datetimes now, which should have been done long time ago.
From my testing this seems to have fixed it, and it will now show as `CET` in the frontend, while backend and DB keeps things in `UTC`. 

Change done in this commit https://github.com/kcapp/api/commit/1da9138e70e2e4ee3cf4f1ecb9c84dc5230ed21d, and available in [kcapp-api:latest](https://hub.docker.com/r/kcapp/api/tags) if you want to test before I release `2.4.0`. (In the process of doing some other bigger changes as well, so might be a `3.0.0`  version)

If you run DB in `CET` I guess it would still cause some issues between `NOW()` and `time.Now().UTC()`, so I would say it's preferred to run DB in `UTC`, if I get some time I can look into fixing this as well later.

Adding `TZ` to Docker containers probably also makes sense
